apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgrespassword@postgres-service:5432/devops_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  POSTGRES_DB: "devops_db"

