apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: devops-app
  labels:
    app: devops-cloud-api
spec:
  type: LoadBalancer # Or NodePort when running on single-node/minikube
  selector:
    app: devops-cloud-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

